# Generated by Django 5.0.2 on 2024-02-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_noise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
