# Generated by Django 5.0.2 on 2024-03-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0007_profile_facebook_link_profile_github_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proflle_bio',
            new_name='profile_bio',
        ),
    ]
